### ISSUE TITLE
Need release to fix incompatibility with latest version of cmd2

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2-submenu#7]
We need to put out a new release to fix an incompatibility with the latest version of cmd2.

@kotfu Can you please add me as a maintainer of the ``cmd2-submenu`` project on PyPI so that I can also put out releases for this plugin in the future?

**Comment by kotfu** [comment]
Done.

**Comment by tleonhardt** [comment]
Thanks.  I’ll try to put out a release tomorrow night.

**Comment by tleonhardt** [comment]
The 0.3.0 release has been published to PyPI with the recent fix.
